Custom completer example
jupyterlab/extension-examples pull request #169
Opened 2021-07-13 23:35 UTC by ohrely

2021-07-14 07:24 UTC, fcollonval requested changes
Thanks for this great example @ohrely 

Some general comment, could you upgrade the example to use the latest cookiecutter template?
You can achieve then thanks to  `scripts/upgrade_extensions.py`

Could you add a note in the readme on the disabling cotr extension feature you are using?

For the tests, there is a big in the ci for the other example. For yours, you need to have some configuration files matching the one in hello world - it should be ok one you upgrade all extensions. And you need to insert the code snippets in the readme using `jlpm run embedme` at the root examples folder.

2021-07-15 22:55 UTC, ohrely commented
> Some general comment, could you upgrade the example to use the latest cookiecutter template?
> You can achieve that thanks to `scripts/upgrade_extensions.py`

@fcollonval When I run this script, it makes modifications to setup.py and package.json in several of the example extensions and adds RELEASE.md to every extension.  Is this the correct behavior?

2021-07-16 06:05 UTC, fcollonval commented
>  Is this the correct behavior?

Yes this is expected as new commits have been pushed to the template project recently. If you can ignore those in the other extensions, it will be appreciated (so this PR keeps focusing on the new example alone).

2021-07-16 22:37 UTC, ohrely commented
The two build_all tests are failing because one inserted code snippet is getting "corrected" by pre-commit linting, so it no longer matches the (more indented) source of the snippet.  Is there a preferred way to address this?

I'm not sure what to make of the three failing build_extensions checks.

2021-07-17 08:52 UTC, fcollonval commented
Thanks for pushing forward

To fix the linter error in the Readme, you should wrap the code snippets between special comments; e.g.

```
<!-- prettier-ignore-start -->
\`\`\`ts // src/index.ts#L12-L14 

activate: (app: JupyterFrontEnd) => { 
console.log('the JupyterLab main application:', app); 
}, 
\`\`\` 
<!-- prettier-ignore-end -->
```

Regarding the remaining error in the new example, you need to overwrite tsconfig.json, .eslintrc.js, .eslintignore and .gitignore with those in the hello-world example (this is to ensure homogenous config).

2021-07-20 10:01 UTC, fcollonval requested changes
Thanks @ohrely I push a commit to fix all linter troubles to go forward. I have two comments in the code and one general one: could you use `you` instead of `we` in the readme?

2021-07-20 10:01 UTC, fcollonval commented on completer/README.md
> +- Try modifying the `completionHint` function to return no matches when `token.value.length` is less than 3.
Some sentence before this, like `This custom connector will behave like this:`

Could you change this part to describe the actual code doing those actions?

2021-07-28 10:01 UTC, hbcarlos commented
Hi @ohrely and @fcollonval, I rebased from master and added a basic test.

I'll update the extension to JupyterLab v3.1 too.

2021-07-29 07:32 UTC, fcollonval commented
@hbcarlos thanks for pushing this one. Could you please add a more advanced ui test that open a notebook, trigger the completer and check the suggestions are the one expected?

2021-08-02 17:53 UTC, hbcarlos commented
@fcollonval I'm not sure where the CI test fail. Do you have any advice?

2021-08-03 05:45 UTC, fcollonval commented
We are getting closer 🙃

The integration test needs to be more robust. Did you try to run it locally before running it in the ci?
Two ideas, the kernel may not be ready when you hit tab. So waiting for the idle state could be good. The other one is that I had some trouble with codemirror edition that I circumvent by using `page.keyboard` - see settings example.

2021-08-03 07:40 UTC, hbcarlos commented
Thanks for the advice, @fcollonval! Yes, I tested locally before pushing to CI.

2021-08-03 07:53 UTC, hbcarlos commented
Btw, when running locally, If you don't run `npx playwright install` first, the test fails because chromium is not installed.

2021-08-03 10:27 UTC, fcollonval commented
Thanks @hbcarlos 

I updated the test to trigger the custom completion and make it more robust.
Plus I catched some missing package not listed in dependencies.

2021-08-03 10:28 UTC, fcollonval approved these changes
Let's merge
Thanks a lot @ohrely and @hbcarlos

2021-08-03 10:28 UTC, merged

2021-08-03 10:29 UTC, hbcarlos commented
Thanks to you for all the help!!

2021-08-04 20:38 UTC, ohrely commented
Thank you both!