Upgrade dependencies and update server-extension install instructions
jupyterlab/extension-examples pull request #175
Opened 2021-07-29 09:41 UTC by hbcarlos

I used the script to upgrade all extensions at once and check that every extension works.

I also modified the installation instructions of the server-extension to to add the enable server extension command.

2021-07-29 11:20 UTC, fcollonval commented
We need to figure out why eslint is broken :'(

2021-07-29 11:21 UTC, hbcarlos commented
Could it be that it is linting files in `node_modules`?

2021-07-29 11:30 UTC, fcollonval commented
> Could it be that it is linting files in `node_modules`?

I don't think so. This project is not freezing its `yarn.lock` file and `eslint` is working on my local copy. But I presume that if the node modules and the `yarn.lock` files were removed, it will raise the same error. This sounds like new eslint dependencies were released that bring issues.

2021-07-29 11:45 UTC, hbcarlos commented
Yeah, I added the `package-lock.json` and it has `eslint v7.31`.

Does the `jupyter-packaging` uses npm if yarn is not installed?

2021-07-29 12:14 UTC, fcollonval commented
> Does the `jupyter-packaging` uses npm if yarn is not installed? Or if you don't indicate the build tool?
> https://github.com/hbcarlos/extension-examples/blob/006053e190f737c911437ab6654bc0ac386cc777/hello-world/setup.py#L70

Yes it does: https://github.com/jupyter/jupyter-packaging/blob/2e22a16559601a6830a2d5bb263be4ccd1a48690/jupyter_packaging/setupbase.py#L189

2021-07-29 12:20 UTC, fcollonval commented
There has been lots of new release around jsdoc lately. Could try updating `eslint-plugin-jsdoc` to `^36.0.0` in all examples? Hopefully this will fix the problem.

2021-07-29 14:54 UTC, hbcarlos commented
Thanks for these tips, @fcollonval.

I think the test failures are coming from the UI tests because of the timeout but I am not sure what to do.

2021-07-30 06:29 UTC, fcollonval commented
> I think the test failures are coming from the UI tests because of the timeout but I am not sure what to do.

The error is probably coming because we are downloading the latest prerelease version of JupyterLab from pypi.org (I needed 3.1). Now that 3.1 has been released, I remove the `--pre` option because it was downloading the 4.0 alpha in which the view menu has changed. That changes make closing the file browser code in the test not working any more.

2021-07-30 12:45 UTC, fcollonval approved these changes
Thanks a lot @hbcarlos :tada:

2021-07-30 12:47 UTC, fcollonval requested changes
Sorry I miss some mistake in the embed snippets

2021-07-30 12:47 UTC, fcollonval commented on server-extension/README.md
> +data_files_spec = [
Line reference needs to be updated

2021-07-30 12:47 UTC, fcollonval commented on server-extension/README.md
> +("share/jupyter/labextensions/%s" % labext_name, str("."), "install.json"),
Line reference needs to be updated

2021-07-30 12:47 UTC, fcollonval commented on server-extension/README.md
> +"jupyter-config/server-config", "jlab_ext_example.json"),
Line reference needs to be updated

2021-07-30 12:48 UTC, fcollonval commented on server-extension/README.md
> +jupyter server extension enable jlab_ext_example
Thanks for correcting that one

2021-07-30 13:32 UTC, hbcarlos commented on server-extension/README.md
> +("share/jupyter/labextensions/%s" % labext_name, str(lab_path.relative_to(HERE)), "**"),
Did you mean this?

2021-08-02 06:43 UTC, fcollonval approved these changes
> Did you mean this?

Yes thanks for correcting them.

2021-08-02 06:43 UTC, merged